user_name     = "admin"
password      = "***"
auth_url      = "http://***:5000/v3"
key_name      = "key-node"
ssh_key       = "***"
network_name  = "Private"
subnet_name   = "Privatesub"
router_name   = "Virtual Router"
secgroup_name = "secgroup1"
num-instance  = 2
image         = "CentOS-7-x86_64"
ip_address    = ["***","***"]
